[package]
name = "gossip"
version = "0.1.0"
edition = "2021"

[features]
# echo = []
# generate = []
broadcast = []

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = { version= "1.0.99"}
uuid = { version= "1.4.0", features = ["v4", "serde"]}
